// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	role "github.com/admgo/admgo/user/api/internal/handler/role"
	"github.com/admgo/admgo/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Num},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/user/role/list",
					Handler: role.UserRoleListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/role/list",
				Handler: role.UserRoleListPHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)
}
