// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: cmdb.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ResourceGroup_CreateResourceGroup_FullMethodName = "/service.ResourceGroup/CreateResourceGroup"
)

// ResourceGroupClient is the client API for ResourceGroup service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResourceGroupClient interface {
	// 创建资源组
	CreateResourceGroup(ctx context.Context, in *CreateResourceGroupRequest, opts ...grpc.CallOption) (*CreateResourceGroupResponse, error)
}

type resourceGroupClient struct {
	cc grpc.ClientConnInterface
}

func NewResourceGroupClient(cc grpc.ClientConnInterface) ResourceGroupClient {
	return &resourceGroupClient{cc}
}

func (c *resourceGroupClient) CreateResourceGroup(ctx context.Context, in *CreateResourceGroupRequest, opts ...grpc.CallOption) (*CreateResourceGroupResponse, error) {
	out := new(CreateResourceGroupResponse)
	err := c.cc.Invoke(ctx, ResourceGroup_CreateResourceGroup_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResourceGroupServer is the server API for ResourceGroup service.
// All implementations must embed UnimplementedResourceGroupServer
// for forward compatibility
type ResourceGroupServer interface {
	// 创建资源组
	CreateResourceGroup(context.Context, *CreateResourceGroupRequest) (*CreateResourceGroupResponse, error)
	mustEmbedUnimplementedResourceGroupServer()
}

// UnimplementedResourceGroupServer must be embedded to have forward compatible implementations.
type UnimplementedResourceGroupServer struct {
}

func (UnimplementedResourceGroupServer) CreateResourceGroup(context.Context, *CreateResourceGroupRequest) (*CreateResourceGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateResourceGroup not implemented")
}
func (UnimplementedResourceGroupServer) mustEmbedUnimplementedResourceGroupServer() {}

// UnsafeResourceGroupServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResourceGroupServer will
// result in compilation errors.
type UnsafeResourceGroupServer interface {
	mustEmbedUnimplementedResourceGroupServer()
}

func RegisterResourceGroupServer(s grpc.ServiceRegistrar, srv ResourceGroupServer) {
	s.RegisterService(&ResourceGroup_ServiceDesc, srv)
}

func _ResourceGroup_CreateResourceGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateResourceGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceGroupServer).CreateResourceGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceGroup_CreateResourceGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceGroupServer).CreateResourceGroup(ctx, req.(*CreateResourceGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ResourceGroup_ServiceDesc is the grpc.ServiceDesc for ResourceGroup service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResourceGroup_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.ResourceGroup",
	HandlerType: (*ResourceGroupServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateResourceGroup",
			Handler:    _ResourceGroup_CreateResourceGroup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cmdb.proto",
}

const (
	ResourceType_CreateResourceType_FullMethodName = "/service.ResourceType/CreateResourceType"
)

// ResourceTypeClient is the client API for ResourceType service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResourceTypeClient interface {
	// 创建资源类型
	CreateResourceType(ctx context.Context, in *CreateResourceTypeRequest, opts ...grpc.CallOption) (*CreateResourceTypeResponse, error)
}

type resourceTypeClient struct {
	cc grpc.ClientConnInterface
}

func NewResourceTypeClient(cc grpc.ClientConnInterface) ResourceTypeClient {
	return &resourceTypeClient{cc}
}

func (c *resourceTypeClient) CreateResourceType(ctx context.Context, in *CreateResourceTypeRequest, opts ...grpc.CallOption) (*CreateResourceTypeResponse, error) {
	out := new(CreateResourceTypeResponse)
	err := c.cc.Invoke(ctx, ResourceType_CreateResourceType_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResourceTypeServer is the server API for ResourceType service.
// All implementations must embed UnimplementedResourceTypeServer
// for forward compatibility
type ResourceTypeServer interface {
	// 创建资源类型
	CreateResourceType(context.Context, *CreateResourceTypeRequest) (*CreateResourceTypeResponse, error)
	mustEmbedUnimplementedResourceTypeServer()
}

// UnimplementedResourceTypeServer must be embedded to have forward compatible implementations.
type UnimplementedResourceTypeServer struct {
}

func (UnimplementedResourceTypeServer) CreateResourceType(context.Context, *CreateResourceTypeRequest) (*CreateResourceTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateResourceType not implemented")
}
func (UnimplementedResourceTypeServer) mustEmbedUnimplementedResourceTypeServer() {}

// UnsafeResourceTypeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResourceTypeServer will
// result in compilation errors.
type UnsafeResourceTypeServer interface {
	mustEmbedUnimplementedResourceTypeServer()
}

func RegisterResourceTypeServer(s grpc.ServiceRegistrar, srv ResourceTypeServer) {
	s.RegisterService(&ResourceType_ServiceDesc, srv)
}

func _ResourceType_CreateResourceType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateResourceTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceTypeServer).CreateResourceType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceType_CreateResourceType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceTypeServer).CreateResourceType(ctx, req.(*CreateResourceTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ResourceType_ServiceDesc is the grpc.ServiceDesc for ResourceType service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResourceType_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.ResourceType",
	HandlerType: (*ResourceTypeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateResourceType",
			Handler:    _ResourceType_CreateResourceType_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cmdb.proto",
}

const (
	ResourceModel_CreateResourceModel_FullMethodName = "/service.ResourceModel/CreateResourceModel"
)

// ResourceModelClient is the client API for ResourceModel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResourceModelClient interface {
	// 创建资源模型
	CreateResourceModel(ctx context.Context, in *CreateResourceModelRequest, opts ...grpc.CallOption) (*CreateResourceModelResponse, error)
}

type resourceModelClient struct {
	cc grpc.ClientConnInterface
}

func NewResourceModelClient(cc grpc.ClientConnInterface) ResourceModelClient {
	return &resourceModelClient{cc}
}

func (c *resourceModelClient) CreateResourceModel(ctx context.Context, in *CreateResourceModelRequest, opts ...grpc.CallOption) (*CreateResourceModelResponse, error) {
	out := new(CreateResourceModelResponse)
	err := c.cc.Invoke(ctx, ResourceModel_CreateResourceModel_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResourceModelServer is the server API for ResourceModel service.
// All implementations must embed UnimplementedResourceModelServer
// for forward compatibility
type ResourceModelServer interface {
	// 创建资源模型
	CreateResourceModel(context.Context, *CreateResourceModelRequest) (*CreateResourceModelResponse, error)
	mustEmbedUnimplementedResourceModelServer()
}

// UnimplementedResourceModelServer must be embedded to have forward compatible implementations.
type UnimplementedResourceModelServer struct {
}

func (UnimplementedResourceModelServer) CreateResourceModel(context.Context, *CreateResourceModelRequest) (*CreateResourceModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateResourceModel not implemented")
}
func (UnimplementedResourceModelServer) mustEmbedUnimplementedResourceModelServer() {}

// UnsafeResourceModelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResourceModelServer will
// result in compilation errors.
type UnsafeResourceModelServer interface {
	mustEmbedUnimplementedResourceModelServer()
}

func RegisterResourceModelServer(s grpc.ServiceRegistrar, srv ResourceModelServer) {
	s.RegisterService(&ResourceModel_ServiceDesc, srv)
}

func _ResourceModel_CreateResourceModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateResourceModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceModelServer).CreateResourceModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceModel_CreateResourceModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceModelServer).CreateResourceModel(ctx, req.(*CreateResourceModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ResourceModel_ServiceDesc is the grpc.ServiceDesc for ResourceModel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResourceModel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.ResourceModel",
	HandlerType: (*ResourceModelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateResourceModel",
			Handler:    _ResourceModel_CreateResourceModel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cmdb.proto",
}

const (
	ResourceAttribute_CreateResourceAttribute_FullMethodName = "/service.ResourceAttribute/CreateResourceAttribute"
)

// ResourceAttributeClient is the client API for ResourceAttribute service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResourceAttributeClient interface {
	// 创建资源属性
	CreateResourceAttribute(ctx context.Context, in *CreateResourceAttributeRequest, opts ...grpc.CallOption) (*CreateResourceAttributeResponse, error)
}

type resourceAttributeClient struct {
	cc grpc.ClientConnInterface
}

func NewResourceAttributeClient(cc grpc.ClientConnInterface) ResourceAttributeClient {
	return &resourceAttributeClient{cc}
}

func (c *resourceAttributeClient) CreateResourceAttribute(ctx context.Context, in *CreateResourceAttributeRequest, opts ...grpc.CallOption) (*CreateResourceAttributeResponse, error) {
	out := new(CreateResourceAttributeResponse)
	err := c.cc.Invoke(ctx, ResourceAttribute_CreateResourceAttribute_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResourceAttributeServer is the server API for ResourceAttribute service.
// All implementations must embed UnimplementedResourceAttributeServer
// for forward compatibility
type ResourceAttributeServer interface {
	// 创建资源属性
	CreateResourceAttribute(context.Context, *CreateResourceAttributeRequest) (*CreateResourceAttributeResponse, error)
	mustEmbedUnimplementedResourceAttributeServer()
}

// UnimplementedResourceAttributeServer must be embedded to have forward compatible implementations.
type UnimplementedResourceAttributeServer struct {
}

func (UnimplementedResourceAttributeServer) CreateResourceAttribute(context.Context, *CreateResourceAttributeRequest) (*CreateResourceAttributeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateResourceAttribute not implemented")
}
func (UnimplementedResourceAttributeServer) mustEmbedUnimplementedResourceAttributeServer() {}

// UnsafeResourceAttributeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResourceAttributeServer will
// result in compilation errors.
type UnsafeResourceAttributeServer interface {
	mustEmbedUnimplementedResourceAttributeServer()
}

func RegisterResourceAttributeServer(s grpc.ServiceRegistrar, srv ResourceAttributeServer) {
	s.RegisterService(&ResourceAttribute_ServiceDesc, srv)
}

func _ResourceAttribute_CreateResourceAttribute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateResourceAttributeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceAttributeServer).CreateResourceAttribute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceAttribute_CreateResourceAttribute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceAttributeServer).CreateResourceAttribute(ctx, req.(*CreateResourceAttributeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ResourceAttribute_ServiceDesc is the grpc.ServiceDesc for ResourceAttribute service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResourceAttribute_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.ResourceAttribute",
	HandlerType: (*ResourceAttributeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateResourceAttribute",
			Handler:    _ResourceAttribute_CreateResourceAttribute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cmdb.proto",
}

const (
	AttributeType_CreateAttributeType_FullMethodName = "/service.AttributeType/CreateAttributeType"
)

// AttributeTypeClient is the client API for AttributeType service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AttributeTypeClient interface {
	// 创建资源属性类型
	CreateAttributeType(ctx context.Context, in *CreateAttributeTypeRequest, opts ...grpc.CallOption) (*CreateAttributeTypeResponse, error)
}

type attributeTypeClient struct {
	cc grpc.ClientConnInterface
}

func NewAttributeTypeClient(cc grpc.ClientConnInterface) AttributeTypeClient {
	return &attributeTypeClient{cc}
}

func (c *attributeTypeClient) CreateAttributeType(ctx context.Context, in *CreateAttributeTypeRequest, opts ...grpc.CallOption) (*CreateAttributeTypeResponse, error) {
	out := new(CreateAttributeTypeResponse)
	err := c.cc.Invoke(ctx, AttributeType_CreateAttributeType_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AttributeTypeServer is the server API for AttributeType service.
// All implementations must embed UnimplementedAttributeTypeServer
// for forward compatibility
type AttributeTypeServer interface {
	// 创建资源属性类型
	CreateAttributeType(context.Context, *CreateAttributeTypeRequest) (*CreateAttributeTypeResponse, error)
	mustEmbedUnimplementedAttributeTypeServer()
}

// UnimplementedAttributeTypeServer must be embedded to have forward compatible implementations.
type UnimplementedAttributeTypeServer struct {
}

func (UnimplementedAttributeTypeServer) CreateAttributeType(context.Context, *CreateAttributeTypeRequest) (*CreateAttributeTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAttributeType not implemented")
}
func (UnimplementedAttributeTypeServer) mustEmbedUnimplementedAttributeTypeServer() {}

// UnsafeAttributeTypeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AttributeTypeServer will
// result in compilation errors.
type UnsafeAttributeTypeServer interface {
	mustEmbedUnimplementedAttributeTypeServer()
}

func RegisterAttributeTypeServer(s grpc.ServiceRegistrar, srv AttributeTypeServer) {
	s.RegisterService(&AttributeType_ServiceDesc, srv)
}

func _AttributeType_CreateAttributeType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAttributeTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttributeTypeServer).CreateAttributeType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttributeType_CreateAttributeType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttributeTypeServer).CreateAttributeType(ctx, req.(*CreateAttributeTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AttributeType_ServiceDesc is the grpc.ServiceDesc for AttributeType service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AttributeType_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.AttributeType",
	HandlerType: (*AttributeTypeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAttributeType",
			Handler:    _AttributeType_CreateAttributeType_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cmdb.proto",
}

const (
	Resource_CreateResource_FullMethodName = "/service.Resource/CreateResource"
)

// ResourceClient is the client API for Resource service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResourceClient interface {
	// 创建资源
	CreateResource(ctx context.Context, in *CreateResourceRequest, opts ...grpc.CallOption) (*CreateResourceResponse, error)
}

type resourceClient struct {
	cc grpc.ClientConnInterface
}

func NewResourceClient(cc grpc.ClientConnInterface) ResourceClient {
	return &resourceClient{cc}
}

func (c *resourceClient) CreateResource(ctx context.Context, in *CreateResourceRequest, opts ...grpc.CallOption) (*CreateResourceResponse, error) {
	out := new(CreateResourceResponse)
	err := c.cc.Invoke(ctx, Resource_CreateResource_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResourceServer is the server API for Resource service.
// All implementations must embed UnimplementedResourceServer
// for forward compatibility
type ResourceServer interface {
	// 创建资源
	CreateResource(context.Context, *CreateResourceRequest) (*CreateResourceResponse, error)
	mustEmbedUnimplementedResourceServer()
}

// UnimplementedResourceServer must be embedded to have forward compatible implementations.
type UnimplementedResourceServer struct {
}

func (UnimplementedResourceServer) CreateResource(context.Context, *CreateResourceRequest) (*CreateResourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateResource not implemented")
}
func (UnimplementedResourceServer) mustEmbedUnimplementedResourceServer() {}

// UnsafeResourceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResourceServer will
// result in compilation errors.
type UnsafeResourceServer interface {
	mustEmbedUnimplementedResourceServer()
}

func RegisterResourceServer(s grpc.ServiceRegistrar, srv ResourceServer) {
	s.RegisterService(&Resource_ServiceDesc, srv)
}

func _Resource_CreateResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServer).CreateResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Resource_CreateResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServer).CreateResource(ctx, req.(*CreateResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Resource_ServiceDesc is the grpc.ServiceDesc for Resource service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Resource_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.Resource",
	HandlerType: (*ResourceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateResource",
			Handler:    _Resource_CreateResource_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cmdb.proto",
}
