// Code generated by goctl. DO NOT EDIT.
// Source: cmdb.proto

package resourceattribute

import (
	"context"

	"github.com/admgo/admgo/services/cmdb/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateAttributeTypeRequest      = pb.CreateAttributeTypeRequest
	CreateAttributeTypeResponse     = pb.CreateAttributeTypeResponse
	CreateResourceAttributeRequest  = pb.CreateResourceAttributeRequest
	CreateResourceAttributeResponse = pb.CreateResourceAttributeResponse
	CreateResourceGroupRequest      = pb.CreateResourceGroupRequest
	CreateResourceGroupResponse     = pb.CreateResourceGroupResponse
	CreateResourceModelRequest      = pb.CreateResourceModelRequest
	CreateResourceModelResponse     = pb.CreateResourceModelResponse
	CreateResourceRequest           = pb.CreateResourceRequest
	CreateResourceResponse          = pb.CreateResourceResponse
	CreateResourceTypeRequest       = pb.CreateResourceTypeRequest
	CreateResourceTypeResponse      = pb.CreateResourceTypeResponse

	ResourceAttribute interface {
		// 创建资源属性
		CreateResourceAttribute(ctx context.Context, in *CreateResourceAttributeRequest, opts ...grpc.CallOption) (*CreateResourceAttributeResponse, error)
	}

	defaultResourceAttribute struct {
		cli zrpc.Client
	}
)

func NewResourceAttribute(cli zrpc.Client) ResourceAttribute {
	return &defaultResourceAttribute{
		cli: cli,
	}
}

// 创建资源属性
func (m *defaultResourceAttribute) CreateResourceAttribute(ctx context.Context, in *CreateResourceAttributeRequest, opts ...grpc.CallOption) (*CreateResourceAttributeResponse, error) {
	client := pb.NewResourceAttributeClient(m.cli.Conn())
	return client.CreateResourceAttribute(ctx, in, opts...)
}
