// Code generated by goctl. DO NOT EDIT.
// Source: cmdb.proto

package resourcegroup

import (
	"context"

	"github.com/admgo/admgo/services/cmdb/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateAttributeTypeRequest      = pb.CreateAttributeTypeRequest
	CreateAttributeTypeResponse     = pb.CreateAttributeTypeResponse
	CreateResourceAttributeRequest  = pb.CreateResourceAttributeRequest
	CreateResourceAttributeResponse = pb.CreateResourceAttributeResponse
	CreateResourceGroupRequest      = pb.CreateResourceGroupRequest
	CreateResourceGroupResponse     = pb.CreateResourceGroupResponse
	CreateResourceModelRequest      = pb.CreateResourceModelRequest
	CreateResourceModelResponse     = pb.CreateResourceModelResponse
	CreateResourceRequest           = pb.CreateResourceRequest
	CreateResourceResponse          = pb.CreateResourceResponse
	CreateResourceTypeRequest       = pb.CreateResourceTypeRequest
	CreateResourceTypeResponse      = pb.CreateResourceTypeResponse

	ResourceGroup interface {
		// 创建资源组
		CreateResourceGroup(ctx context.Context, in *CreateResourceGroupRequest, opts ...grpc.CallOption) (*CreateResourceGroupResponse, error)
	}

	defaultResourceGroup struct {
		cli zrpc.Client
	}
)

func NewResourceGroup(cli zrpc.Client) ResourceGroup {
	return &defaultResourceGroup{
		cli: cli,
	}
}

// 创建资源组
func (m *defaultResourceGroup) CreateResourceGroup(ctx context.Context, in *CreateResourceGroupRequest, opts ...grpc.CallOption) (*CreateResourceGroupResponse, error) {
	client := pb.NewResourceGroupClient(m.cli.Conn())
	return client.CreateResourceGroup(ctx, in, opts...)
}
