env: "dev"
name: "admgo"
http:
  listen: ":8080"
log:
  level: "debug"

redis:
  default:
    write:
      addr: "127.0.0.1:3309"
      password: ""
      pool_size: 10
      idle_timeout: '5000ms' # uint: ms
      read_timeout: '3000ms' # uint: ms
      write_timeout: '3000ms' # uint: ms
      min_idle_conns: 5
      retries: 3 # content retry count
      db: 0
    read:
      addr: "127.0.0.1:3309"
      password: ""
      pool_size: 10
      idle_timeout: '5000ms' # uint: ms
      min_idle_conns: 5
      read_timeout: '3000ms' # uint: ms
      write_timeout: '3000ms' # uint: ms
      retries: 3 # content retry count
      db: 0

db:
  default:
    log:
      enable: true
      level: "info"
      format: "json" # json or text
      type: "stdout" # stdout or file
      path: "log/db/sql-default.log"
    write:
      enable_sql:
      host: "10.17.25.162"
      port: "3306"
      database: "mysql"
      username: "admgo"
      password: "m9uSFL7duAVXfeAwGUSG"
      charset: "utf8mb4"
      timeout: 50000        # connect db timeout, unit: ms
      write_time_out: 50000  # write data timeout, unit: ms
      read_time_out: 50000   # read data timeout, unit: ms
      max_idle_conns: 5      # the max idle connect count
      max_open_conns: 1000      # the max open connect count
    read:
      host: ""
      port: "3306"
      database: ""
      username: ""
      password: ""
      charset: "utf8mb4"
      timeout: 50000        # connect db timeout, unit: ms
      write_time_out: 50000  # write data timeout, unit: ms
      read_time_out: 50000   # read data timeout, unit: ms
      max_idle_conns: 5      # the max idle connect count
      max_open_conns: 1000      # the max open connect count
  # :
web_server_log:
  enable: true
  log_id_show_header: true
  log_path: "logs/access.log"
  log_format: "text" # text, json
  output: "file" # file, stdout
  skip_paths:
    - "/favicon.ico"
