// Code generated by goctl. DO NOT EDIT.
// Source: cmdb.proto

package server

import (
	"context"

	"github.com/admgo/admgo/services/cmdb/rpc/internal/logic/resourcemodel"
	"github.com/admgo/admgo/services/cmdb/rpc/internal/svc"
	"github.com/admgo/admgo/services/cmdb/rpc/pb"
)

type ResourceModelServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedResourceModelServer
}

func NewResourceModelServer(svcCtx *svc.ServiceContext) *ResourceModelServer {
	return &ResourceModelServer{
		svcCtx: svcCtx,
	}
}

// 创建资源模型
func (s *ResourceModelServer) CreateResourceModel(ctx context.Context, in *pb.CreateResourceModelRequest) (*pb.CreateResourceModelResponse, error) {
	l := resourcemodellogic.NewCreateResourceModelLogic(ctx, s.svcCtx)
	return l.CreateResourceModel(in)
}
