// Code generated by goctl. DO NOT EDIT.
// Source: cmdb.proto

package server

import (
	"context"

	"github.com/admgo/admgo/services/cmdb/rpc/internal/logic/resourcetype"
	"github.com/admgo/admgo/services/cmdb/rpc/internal/svc"
	"github.com/admgo/admgo/services/cmdb/rpc/pb"
)

type ResourceTypeServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedResourceTypeServer
}

func NewResourceTypeServer(svcCtx *svc.ServiceContext) *ResourceTypeServer {
	return &ResourceTypeServer{
		svcCtx: svcCtx,
	}
}

// 创建资源类型
func (s *ResourceTypeServer) CreateResourceType(ctx context.Context, in *pb.CreateResourceTypeRequest) (*pb.CreateResourceTypeResponse, error) {
	l := resourcetypelogic.NewCreateResourceTypeLogic(ctx, s.svcCtx)
	return l.CreateResourceType(in)
}
