// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	UserName string `json:"username"`
	PassWord string `json:"password"`
}

type LoginRsp struct {
	Msg string `json:"msg"`
}

type LogoutReq struct {
	UserName string `json:"username"`
}

type LogoutRsp struct {
	Msg string `json:"msg"`
}
