// Code generated by goctl. DO NOT EDIT.
package types

type BaseRsp struct {
	Code int32       `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data,omitempty"`
}

type LoginReq struct {
	UserName string `json:"username,options=[foo,bar]"`
	PassWord string `json:"password"`
}

type LoginRsp struct {
	BaseRsp
}

type LogoutReq struct {
	UserName string `json:"username"`
}

type LogoutRsp struct {
	BaseRsp
}
