// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	UserName string `json:"username,optional" validate:"required"`
	PassWord string `json:"password,optional"`
}

type LoginRsp struct {
	PassWord string `json:"password,optional"`
}

type LogoutReq struct {
	UserName string `json:"username,optional"`
}

type LogoutRsp struct {
}
