// Code generated by goctl. DO NOT EDIT.
// Source: cmdb.proto

package attributetype

import (
	"context"

	"github.com/admgo/admgo/services/cmdb/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateAttributeTypeRequest      = pb.CreateAttributeTypeRequest
	CreateAttributeTypeResponse     = pb.CreateAttributeTypeResponse
	CreateResourceAttributeRequest  = pb.CreateResourceAttributeRequest
	CreateResourceAttributeResponse = pb.CreateResourceAttributeResponse
	CreateResourceGroupRequest      = pb.CreateResourceGroupRequest
	CreateResourceGroupResponse     = pb.CreateResourceGroupResponse
	CreateResourceModelRequest      = pb.CreateResourceModelRequest
	CreateResourceModelResponse     = pb.CreateResourceModelResponse
	CreateResourceRequest           = pb.CreateResourceRequest
	CreateResourceResponse          = pb.CreateResourceResponse
	CreateResourceTypeRequest       = pb.CreateResourceTypeRequest
	CreateResourceTypeResponse      = pb.CreateResourceTypeResponse

	AttributeType interface {
		// 创建资源属性类型
		CreateAttributeType(ctx context.Context, in *CreateAttributeTypeRequest, opts ...grpc.CallOption) (*CreateAttributeTypeResponse, error)
	}

	defaultAttributeType struct {
		cli zrpc.Client
	}
)

func NewAttributeType(cli zrpc.Client) AttributeType {
	return &defaultAttributeType{
		cli: cli,
	}
}

// 创建资源属性类型
func (m *defaultAttributeType) CreateAttributeType(ctx context.Context, in *CreateAttributeTypeRequest, opts ...grpc.CallOption) (*CreateAttributeTypeResponse, error) {
	client := pb.NewAttributeTypeClient(m.cli.Conn())
	return client.CreateAttributeType(ctx, in, opts...)
}
