// Code generated by goctl. DO NOT EDIT.
// Source: cmdb.proto

package resourcetype

import (
	"context"

	"github.com/admgo/admgo/services/cmdb/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateAttributeTypeRequest      = pb.CreateAttributeTypeRequest
	CreateAttributeTypeResponse     = pb.CreateAttributeTypeResponse
	CreateResourceAttributeRequest  = pb.CreateResourceAttributeRequest
	CreateResourceAttributeResponse = pb.CreateResourceAttributeResponse
	CreateResourceGroupRequest      = pb.CreateResourceGroupRequest
	CreateResourceGroupResponse     = pb.CreateResourceGroupResponse
	CreateResourceModelRequest      = pb.CreateResourceModelRequest
	CreateResourceModelResponse     = pb.CreateResourceModelResponse
	CreateResourceRequest           = pb.CreateResourceRequest
	CreateResourceResponse          = pb.CreateResourceResponse
	CreateResourceTypeRequest       = pb.CreateResourceTypeRequest
	CreateResourceTypeResponse      = pb.CreateResourceTypeResponse

	ResourceType interface {
		// 创建资源类型
		CreateResourceType(ctx context.Context, in *CreateResourceTypeRequest, opts ...grpc.CallOption) (*CreateResourceTypeResponse, error)
	}

	defaultResourceType struct {
		cli zrpc.Client
	}
)

func NewResourceType(cli zrpc.Client) ResourceType {
	return &defaultResourceType{
		cli: cli,
	}
}

// 创建资源类型
func (m *defaultResourceType) CreateResourceType(ctx context.Context, in *CreateResourceTypeRequest, opts ...grpc.CallOption) (*CreateResourceTypeResponse, error) {
	client := pb.NewResourceTypeClient(m.cli.Conn())
	return client.CreateResourceType(ctx, in, opts...)
}
